# Generated by Django 4.2.1 on 2023-07-08 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="title",
        ),
    ]
